sudo: required
language: generic
services: [docker]

install:
  - docker build --tag test-image .
  - docker run --detach --interactive --name test-image-container --volume "$(pwd)":/tmp/venom --workdir /tmp/venom test-image

script:
  - docker exec test-image-container meson build
  - docker exec test-image-container ninja -C build

after_script:
  - docker images
