---
version: 2.1
commands:
  debian-install-deps:
    steps:
      - run:
          name: Install dependencies
          command: apt update
            && apt install -y
              clang
              cmake
              libconfig-dev
              libgtest-dev
              libopus-dev
              libsodium-dev
              libvpx-dev
              pkg-config
              libgee-0.8-dev
              libgspell-1-dev
              libgtk-3-dev
              libjson-glib-dev
              libsoup2.4-dev
              libsqlcipher-dev
              libcanberra-dev
              libgstreamer1.0-dev
              libgstreamer-plugins-base1.0-dev
              valac
              python3-pip
              wget
      - run:
          name: Install meson
          command: pip3 install meson ninja
  fedora-install-deps:
    steps:
      - run:
          name: Install dependencies
          command: dnf install -y
              clang
              make
              cmake
              libconfig-devel
              gtest-devel
              opus-devel
              libsodium-devel
              libvpx-devel
              pkgconfig
              libgee-devel
              gspell-devel
              gtk3-devel
              json-glib-devel
              libsoup-devel
              sqlcipher-devel
              libcanberra-devel
              gstreamer1-devel
              gstreamer1-plugins-base-devel
              vala
              python3-pip
              wget
      - run:
          name: Install meson
          command: pip3 install meson ninja
  install-toxcore:
    steps:
      - run:
          name: Build and install toxcore
          command: |
            wget "https://github.com/TokTok/c-toxcore/archive/v0.2.9.tar.gz"
            tar -xzf v0.2.9.tar.gz
            cd c-toxcore-0.2.9
            cmake -DCMAKE_INSTALL_PREFIX=/usr
            make
            make install
            cd ..
  install-venom:
    steps:
      - run:
          name: Configure
          command: meson build
      - run:
          name: Build
          command: ninja -C build
      - run:
          name: Test
          command: ninja -C build test
      - run:
          name: Install
          command: ninja -C build install
jobs:
  "Ubuntu 18-04":
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - debian-install-deps
      - install-toxcore
      - install-venom
  "Ubuntu 18-10":
    docker:
      - image: ubuntu:18.10
    steps:
      - checkout
      - debian-install-deps
      - install-toxcore
      - install-venom
  "Debian 9":
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - debian-install-deps
      - install-toxcore
      - install-venom
  "Debian 10":
    docker:
      - image: debian:buster
    steps:
      - checkout
      - debian-install-deps
      - install-toxcore
      - install-venom
  "Fedora 28":
    docker:
      - image: fedora:28
    steps:
      - checkout
      - fedora-install-deps
      - install-toxcore
      - install-venom
  "Fedora 29":
    docker:
      - image: fedora:29
    steps:
      - checkout
      - fedora-install-deps
      - install-toxcore
      - install-venom
workflows:
  version: 2
  build:
    jobs:
      - "Ubuntu 18-04"
      - "Ubuntu 18-10"
      # - "Debian 9" // FIXME requires a vala update
      - "Debian 10"
      - "Fedora 28"
      - "Fedora 29"